tasks:
  - before: cd backend
  - command: yarn init
  - openMode: split-right
    command: echo "SplitTerminal"
  - openIn: left
    command: echo "LeftPanelTerminal"
image:
  file: .gitpod.Dockerfile
