tasks:
  - before: cd backend
    command: yarn
  - openMode: split-right
    before: cd frontend
    command: yarn
  - openMode: split-right
    before: cd mobile
    command: echo "Mobile Terminal"
image:
  file: .gitpod.Dockerfile
