tasks:
  - before: cd backend
    command: yarn
  - openMode: split-right
    before: cd frontend
    command: yarn"
  - openMode: split-right
    before: cd mobile

image:
  file: .gitpod.Dockerfile
